### PUT blog by ID
PUT http://localhost:8080/blogs/1
Content-Type: applciation/json

{"title":"Third Blog","content":"This is the third blog"}

### PUT blog not found
PUT http://localhost:8080/blogs/a
Content-Type: applciation/json

{"title":"Third Blog","content":"This is the third blog"}